runmode: debug

db:
  name: bluebell
  addr: 192.168.28.173:3305
  username: root
  password: 123456

log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: logs/log.log
  log_format_text: false
  rollingPolicy: size # size, daily
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7